### ISSUE TITLE
Modules?

### ISSUE THREAD

**Issue by excitedbox** [jtylek/EpesiCRM#10]
Isn't it kind of dumb to hide the premium store? An Apps ecosystem is a MAJOR selling point yet you have chosen not to list the store/modules on the website or make them viewable through the Admin interface. If I am trying to sell something I make it as easy as possible because nobody is going to jump through hoops just to see if their needs are met by some solution when there is tons of free competition around.

**Comment by jtylek** [comment]
I apologize for this, you are 100% right. Unfortunately I had some health problems caused by police brutal beating:
https://www.youtube.com/watch?v=vf9PuTOvy2Q
and I am recovering from it. This is why our web site is in disarray. But we are working on updated version.
In addition I will be releasing Warehouse Management System and Accounting modules as open source, free of charge.
https://github.com/jtylek/EpesiWarehouse
